name: Random Cron
on:
  workflow_run:
    workflows: ["刷步数"]
    types:
      - completed
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11,需要repo和workflow权限
      
      - name: Update README
        run: |
          echo "- Auto Sign-in run successful on $(date)" >> README.md

      - name:  Commit and push changes
        run: |
          # git commit
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "random cron"
          git push origin master
          
